<?php

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_page_attachments_alter().
 *
 * Adds hashtag js to frontpage
 */
function itkore_frontpage_hashtag_page_attachments_alter(array &$page) {
  if(\Drupal::service('path.matcher')->isFrontPage()) {
    $page['#attached']['library'][] = 'itkore_frontpage_hashtag/itkore-frontpage-hashtag';
  }
}


/**
 * Implements hook_form_formID_alter.
 */
function itkore_frontpage_hashtag_form_itkore_settings_alter(&$form, FormStateInterface $form_state) {
  // Get itkore config.
  $config = \Drupal::getContainer()->get('itkore_base.itkore_config');

  // Add hashtag field to form.
  $form['frontpage_wrapper']['frontpage_hashtag'] = array(
    '#title' => t('Frontpage hashtag'),
    '#type' => 'textfield',
    '#default_value' => $config->get('itkore_frontpage.frontpage_hashtag',''),
    '#weight' => '6',
  );

  // Add an additional submit function call.
  $form['#submit'][] = 'itkore_frontpage_hashtag_submit';
}


/**
 * Custom submit handler for hashtag field.
 */
function itkore_frontpage_hashtag_submit(array &$form, FormStateInterface $form_state) {
  // Get itkore config.
  $config = \Drupal::getContainer()->get('itkore_base.itkore_config');

  // Set config form from form.
  $config->set('itkore_frontpage.frontpage_hashtag', $form_state->getValue('frontpage_hashtag'));
}