<?php

use Drupal\Core\Config;
use Drupal\file\Entity\File;


/**
 * Implements hook_preprocess_page()
 *
 * @param $variables
 *
 */
function itkore_views_settings_preprocess_page (&$variables) {
  // Fetch itkore settings.
  $config = \Drupal::getContainer()->get('itkore_base.itkore_config');

  // Contact page variables for page template.
  if (isset($config)) {
    // Fetch contact image file.
    $image_id = $config->get('itkore_views.news_image');
    $file = ($image_id) ? File::load($image_id) : FALSE;

    $variables['news_title'] = $config->get('itkore_views.news_title');
    $variables['news_image'] = ($file) ? $file->url() : FALSE;
  }
}